---
abstract: 'Max dependencies for Benchmark::Perl::Formance'
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-PerlFormance
requires:
  AAAA::Mail::SpamAssassin: 0
  Benchmark::Perl::Formance: 0
  Benchmark::Perl::Formance::Cargo: 0
  Clone: 0
  Crypt::Primes: 0
  Data::DPath: 0
  DateTime::Calendar::Mayan: 0
  Devel::Size: 0
  Digest::SHA1: 0
  Encode: 0
  ExtUtils::CppGuess: 0
  File::ShareDir: 0
  HTTP::Headers: 0
  Locale::US: 0
  Mail::SpamAssassin: 0
  Math::GMP: 0
  Math::MatrixReal: 0
  Math::Primality: 0
  Module::Build: 0
  Moose: 0
  MooseX::Declare: 0
  Mouse: 0
  POSIX::Regex: 0
  Perl::Critic: 0
  Regexp::Common: 0
  Safe: 0
  Tapper::TestSuite::Benchmark::Perl::Formance: 0
  Test::More: 0
  Text::Balanced: 0
  URI: 0
  YAML::XS: 0
  re::engine::Lua: 0
  re::engine::Oniguruma: 0
  re::engine::Plan9: 0
  re::engine::RE2: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-PerlFormance
  homepage: http://metacpan.org/release/Task-PerlFormance
  repository: git://github.com/renormalist/Task-PerlFormance.git
version: 0.004
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@SCHWIGON/@Basic/GatherDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@SCHWIGON/@Basic/PruneCruft'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@SCHWIGON/@Basic/ManifestSkip'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@SCHWIGON/@Basic/MetaYAML'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::License
      name: '@SCHWIGON/@Basic/License'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@SCHWIGON/@Basic/Readme'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@SCHWIGON/@Basic/ExtraTests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@SCHWIGON/@Basic/ExecDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@SCHWIGON/@Basic/ShareDir'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@SCHWIGON/@Basic/MakeMaker'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@SCHWIGON/@Basic/Manifest'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@SCHWIGON/@Basic/TestRelease'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@SCHWIGON/@Basic/ConfirmRelease'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@SCHWIGON/@Basic/UploadToCPAN'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@SCHWIGON/MetaConfig'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@SCHWIGON/MetaJSON'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@SCHWIGON/PkgVersion'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@SCHWIGON/PodSyntaxTests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@SCHWIGON/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@SCHWIGON/PodCoverageTests'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@SCHWIGON/MetaResources'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@SCHWIGON/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@SCHWIGON/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@SCHWIGON/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@SCHWIGON/AutoPrereqs'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@SCHWIGON/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@SCHWIGON/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@SCHWIGON/NextRelease'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@SCHWIGON/Git::CheckFor::CorrectBranch'
      version: 0.004
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@SCHWIGON/Git::NextVersion'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@SCHWIGON/@Git/Check'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@SCHWIGON/@Git/Commit'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@SCHWIGON/@Git/Tag'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@SCHWIGON/@Git/Push'
      version: 1.122530
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300023
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300023
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300023
x_authority: cpan:SCHWIGON
